config/routes.rb
Billing::Application.routes.draw do
  get "client/index"

  get "client/show"
  

     resources :user ,:except=>"show" do
       collection do
         get   :logout
         get   :login
         post  :send_login
       end
   end
   
   
     namespace :master do
       resources :catagories do
          get     :destroy_catagory
       end
       resources :customer do
         get     :destroy_cutomer 
       end

       resources :employees do
         get     :destroy_employee 
       end

       resources :client do
         get     :destroy_client
       end
       resources :item do
         get     :destroy_item
       end
     end

   root :to => 'user#login'

end

app/models/catagory.rb
class Catagory < ActiveRecord::Base
end

app/models/master.rb
module Master
  def self.table_name_prefix
    'master_'
  end
end

app/controllers/master/catagories_controller.rb
class Master::CatagoriesController < ApplicationController
  
  def index
    @catagory = Catagory.new
  end
  
  def edit
    @catagory = Catagory.find(params[:id])
    @action = 'update'
    render  :action => 'index'
  end
  
  def create
    @catagoryy = Catagory.new(params[:catagory])
    if @catagoryy.save && @catagoryy.update_code
      flash[:notice]= " Catagory Created Sucessfully" 
       redirect_to :action => 'index'
    end
  end
  
  def update
    @catorgy = Catagory.find(params[:id])
    if @catorgy.update_attributes(params[:catogary])
      render :action => 'index'
    end
  end
  
   def destroy_catagory
   @delete_catagory = Catagory.find(params[:catagory_id])
   @delete_catagory.destroy
   flash[:notice] = "Catogary  removed sucessfully"
   redirect_to :action=> 'index'
   end
  
end

app/controllers/master/client_controller.rb
class Master::ClientController < ApplicationController
  def index
    @client = Client.new
  end

  def create
    @client = Client.new(params[:client])
    if @client.save && @client.update_code
       @client.address_details.build(params[:address])
       @client.save
       redirect_to(master_client_index_path(@client), :status=> :found, :notice => "New Client created sucessfully") 
     else
      render 'new'
     end
  end
  
  def edit
    @client = Client.find(params[:id])
    @address = @client.address_details.first
    @action = 'update'
    render :action=> 'index'
  end
  
  def destroy_client
    @client = Client.find(params[:client_id])  
    @client.destroy
    flash[:notice] = "Client removed sucessfully"
    render :action=> 'index'
  end
  
  def update
    @clientt = Client.find(params[:id])
    if @clientt.update_attributes(params[:client])
       @clientt.address_details.build(params[:address])
       @clientt.save
       flash[:notice] = "Client Updated sucessfully"
       render :action => 'index'
    end
  end
  
end

app/controllers/master/customer_controller.rb
class Master::CustomerController < ApplicationController
  
  def index
    @customer = Customer.new
    @action = 'create'
  end
  
  def create
    @customer = Customer.new(params[:customer])
    if @customer.save
      @customer.address_details.build(params[:address])
      @customer.save && @customer.update_code
       redirect_to(master_customer_index_path)
    end
  end
  
  def edit
    @customer = Customer.find(params[:id])
    @address = @customer.address_details.last
    @action = 'update'
    render :action=> 'index'
  end
  
  def update
    @customerr = Customer.find(params[:id])
    if @customerr.update_attributes(params[:customer])
      @customerr.address_details.build(params[:address])
      @customerr.save
      redirect_to :action => 'index'
    end
  end
  
 def destroy_cutomer
 @customer = Customer.find(params[:customer_id])
 @customer.destroy
 flash[:notice] = "Customer removed sucessfully"
 render :action=> 'index'
 end

end

app/controllers/master/employees_controller.rb
#include 'abaranji'

class Master::EmployeesController < ApplicationController
  
  def index
    @employee = Employee.new
    @action = 'create'
  end
  
  def new
    @employee = Employee.new(params[:employee])
  end
  
  def create
    @employe = Employee.new(params[:employee])
    if @employe.save && @employe.update_code
      @employe.address_details.build(params[:address])
      @employe.save
      redirect_to(master_employees_path)
    end
  end
  
  def show
    @employee = Employee.find(params[:employee])
  end
  
  def edit
    @employee = Employee.find(params[:id])
    @action = 'update'  
    render :action => 'index', :id => @employee
  end
  
  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      @employee.address_details.build(params[:address])
      @employee.save
      redirect_to :action => 'index', :id => @employee
    end
  end
  
  def destroy_employee
    @employee = Employee.find(params[:employee_id])
    @employee.destroy
    redirect_to :action => 'index'
  end
end

app/controllers/master/item_controller.rb
class Master::ItemController < ApplicationController
    # include CommanMethods
  def index
    @item = Item.new
    
  end
  
  def new
    
  end
  
  def create
    @item = Item.new(params[:item])
    if @item.save
      @item.update_code
      redirect_to :action => 'index',:notice=> @item.item_name + " Created Successfully"
    end
  end
  
  def edit
    @item = Item.find(params[:id])
    @action = 'update'
    render :action=> 'index'
  end
  
  def update
    @itemm = Item.find(params[:id])
    if @itemm.update_attributes(params[:item])
     redirect_to :action => 'index'
    end
  end
  
 def destroy_item
   @item = Item.find(params[:item_id])
   @item.destroy
   flash[:notice] = "Item removed sucessfully"
   redirect_to :action=> 'index'
 end
  
end

app/helpers/master/catagories_helper.rb
module Master::CatagoriesHelper
end

app/helpers/master/client_helper.rb
module Master::ClientHelper
end

app/helpers/master/customer_helper.rb
module Master::CustomerHelper
end

app/helpers/master/employees_helper.rb
module Master::EmployeesHelper
end

app/helpers/master/item_helper.rb
module Master::ItemHelper
end

app/views/master/catagories/_form.html.erb
<% action = !action.blank? ?  action : 'create'%>
<fieldset> 	
 	<legend><h3><%= action.titleize  + " " + legend %></h3></legend>
    <%= form_for :catagory,:url=>{:action=>action},:method=> type,:html => { :class => "form label-inline uniform"} do |f| %>
		<div class="field"><label for="">Code </label> <%= f.text_field 'code',  :cols => 20,:class=>"medium",:value=> action != 'update' ? Catagory.generate_code : @catagory.code,:readonly=>true  %></div>
		<div class="field1"><label for="">Catagory Name </label> <%= f.text_field 'name',  :cols => 20,:class=>"medium"%></div>
		<br><br><br>
		<div class="buttonrow">
			<button class="btn btn-black" style="margin-right: 200px"><%= action_name %></button>
	    </div>	
    <% end %>	
    
</fieldset>

app/views/master/catagories/index.html.erb
		
		<div class="grid10">
			<%= render :partial=>"form",:locals=>{:legend=>'Category',:action=>@action, :type => @action != 'update' ? 'post' : 'put', :action_name => @action != 'update' ? 'Add' : 'Modify'}%>	
		<br><br><br>
		</div>
           
           
			<table class="data display datatable" id="example">
					<thead>
						<tr>
							<th>S.No</th>
							<th>Code</th>
							<th>Catagory</th>
							<th>Edit</th>
							<th>Delete</th>
						</tr>
					</thead>
					<tbody>
						<% seriel_no = 0 %>
						<% Catagory.all.each do |catagory|%>
						<tr>
						<td><%= seriel_no += 1%></td>
						<td><%= catagory.code%></td>
						<td><%= catagory.name%></td>
						<td><%= link_to 'Edit Catagory', edit_master_catagory_path(catagory) %></td>
						<td><%= link_to 'Remove Catagory', master_catagory_destroy_catagory_path(catagory), :confirm => 'Are you sure?' %></td>
					    <tr>
					    <% end %>	
					</tbody>

					
				</table>

app/views/master/catagories/new.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>Untitled Document</title>
	</head>
	<body>
	</body>
</html>