config/routes.rb
Billing::Application.routes.draw do
  get "client/index"

  get "client/show"
  

     resources :user ,:except=>"show" do
       collection do
         get   :logout
         get   :login
         post  :send_login
       end
   end
   
   
     namespace :master do
       resources :catagories do
          get     :destroy_catagory
       end
       resources :customer do
         get     :destroy_cutomer 
       end

       resources :employees do
         get     :destroy_employee 
       end

       resources :client do
         get     :destroy_client
       end
       resources :item do
         get     :destroy_item
       end
     end

   root :to => 'user#login'

end

app/models/address_detail.rb
class AddressDetail < ActiveRecord::Base
  belongs_to :addressable, :polymorphic => true

end

app/models/catagory.rb
class Catagory < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :address_details, :as => 'addressable'
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :address_details, :as => 'addressable'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
    has_many :address_details, :as => 'addressable', :dependent => :delete_all 
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/master.rb
module Master
  def self.table_name_prefix
    'master_'
  end
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/uniqueid.rb
class Uniqueid < ActiveRecord::Base
  
  
end

app/models/user.rb
# require 'my_module'
# load 'my_module.rb'

class User < ActiveRecord::Base
   include CommanMethods
   has_many :address_details, :as => 'addressable'
   
   
   attr_accessor    :password
   attr_accessible  :name,:password

  
  validates_presence_of :email,:password,:name
  validates_uniqueness_of :name
  validates_confirmation_of :password,:email
   
   
   before_create :change_password
   after_create :unchange_password
   

   def change_password
    self.hashed_password = User.hash_pasword(self.password)
  end
  
  def unchange_password
    password = nil
  end
  
  def self.login(name,password)
    hashed_pasword  = hash_pasword(password || "")
    self.find(:first,:conditions =>["name =? and hashed_password =?",name,hashed_pasword])
  end
  
  def try_to_login
    User.login(self.name,self.password)
  end
  
  private  #------------------------
  
   def self.hash_pasword(password)
     Digest::SHA1.hexdigest(password)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery
 before_filter :authorize_access , :except => [:login, :send_login]
   layout 'menu',:except=>['login'] 
  
  
  def get_code
    Uniqueid.where(:class_name => self.name).last
  end  
  private #-----------------------
  
  
  def authorize_access
   if not session[:user_id]
      flash[:message] = "please Login to access other links"
      redirect_to(:controller => 'user', :action => 'login')
      return  false
   end  
 end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController

#  respond_to :html, :xml, :json
  
  def index
    @user = User.all
    
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def login
  end

  def send_login
    @user = User.new(params[:user])
    logged_in_user = @user.try_to_login
    if logged_in_user
      session[:user_id] = logged_in_user.id
      flash[:notice] = "You are now Logged in"
      redirect_to(user_index_path(@user), :status=> :found, :notice => "You hav loged in ") 
      
    else
      flash[:error] = "Incorrect Username and password"
      redirect_to login_user_index_path
    end
  end

  def menu
  end

  def create
     @user = User.new(params[:user])
     @user.email=  params[:user][:email]
     if @user.save
       redirect_to(user_index_path(@user), :status=> :found, :notice => "New User created sucessfully") 
     else
      render 'new'
     end
  end
 
 def destroy
  @user = User.find(params[:id])
  @user.destroy
  redirect_to(user_index_path(@user), :status=> :found, :notice => "User removed sucessfully")
 end

 def update
  @user = User.find(params[:id])
   @user.update_attributes(params[:user])
    if @user.update_attributes(params[:user])
      
       redirect_to(user_index_path(@user), :status=> :found, :notice => @user.name + "Details updated sucessfully") 
     else
      render 'edit'
     end
 end

 def logout
    session[:user_id] = nil
     flash[:notice] = "you are Logged out sucessfully"
     redirect_to :action => 'login'
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/master/client_helper.rb
module Master::ClientHelper
end

app/helpers/master/customer_helper.rb
module Master::CustomerHelper
end

app/helpers/master/employees_helper.rb
module Master::EmployeesHelper
end

app/helpers/master/item_helper.rb
module Master::ItemHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_form.html.erb
		
			<% if @user.errors.any? %><div class="validation">
				<% @user.errors.full_messages.each do |msg| %>
                   <li ><%= msg %></li>
                 <% end %></div>
			 <% end%>
		
		<table border=1 width="100%" cellspacing=30>
		   	<tr>
		   		<td><label>First Name</label></td>
				<td> <%= f.text_field "first_name"%></td>
				<td>Last Name</td>
				<td><%= f.text_field "last_name"%></td>
		   	</tr>
		  	<tr>
		   		<td>User Name</td>
				<td><%= f.text_field "name",:placeholder=>"user name"%></td>
				<td>Password</td>
				<td><%= f.password_field "password",:placeholder=>"password"%></td>
		   	</tr>
			<tr>
		   		<td>Confirm password</td>
				<td><%= f.password_field "password_confirmation"%></td>
				<td> Is Admin</td>
				<td><%= f.check_box  "is_admin" %></td>
		   	</tr>
			
			<tr>
		   		<td>Email</td>
				<td><%= f.text_field "email"%></td>
				<td>Confirm Email</td>
				<td><%= f.text_field "email_confirmation"%></td>
		   	</tr>
			<tr>
			</tr>	
			<tr>
				<td><td>
				<td><%= f.submit option,:class=>"btn btn-black",:id=>'submit1' %></td>
				<td></td>
				<td></td> 
			</tr>
     </table>
	 </fieldset>
	 
	 <script>
	 	$(document).ready(function(){
				$("submit2").click(function(){
					alert(1)
				});
			});
	 </script>

app/views/user/_user.html.erb
		<table class="data display datatable" id="example">
			aa		<thead>
						<tr>
							<th>S.No</th>
							<th>Name</th>
							<th>Email</th>
							<th>Edit</th>
							<th>Delete</th>
						</tr>
					</thead>
					<tbody>
						<% s_no = 0%>
                       <% @user.each do |user|%>
					     <% s_no += 1%>
					     <tr class="<%= cycle("odd gradeX", "even gradeC") %>">
					     	<td><%= s_no %></td>
					     	<td><%= user.name%></td>
							<td><%= user.email%></td>
							<td><%= link_to 'Edit User', edit_user_path(user) %></td>
							<td><%= link_to 'Remove User', user, :confirm => 'Are you sure?', :method => :delete,:remote=>true %></td>
					     </tr>
						 
					   <% end %>
					</tbody>
				</table>
				
				<div id="example"><b><%= link_to 'Create New User', new_user_path %></b> </div>
<div id="comments">
  <%= render @user %>
</div

app/views/user/edit.html.erb
		<%= form_for :user,:url=>user_path(@user),:method=>:put do |f| %>
		   <%= render :partial=>"form",:locals=>{:option=>"Edit User",:legend=>"Update user",:f=>f}%>
	    <% end %>

app/views/user/index.html.erb
		<table class="data display datatable" id="example">
			aa		<thead>
						<tr>
							<th>S.No</th>
							<th>Name</th>
							<th>Email</th>
							<th>Edit</th>
							<th>Delete</th>
						</tr>
					</thead>
					<tbody>
						<% s_no = 0%>
                       <% @user.each do |user|%>
					     <% s_no += 1%>
					     <tr class="<%= cycle("odd gradeX", "even gradeC") %>">
					     	<td><%= s_no %></td>
					     	<td><%= user.name%></td>
							<td><%= user.email%></td>
							<td><%= link_to 'Edit User', edit_user_path(user) %></td>
							<td><%= link_to 'Remove User', user, :confirm => 'Are you sure?',:remote=>true %></td>
					     </tr>
						 
					   <% end %>
					</tbody>
				</table>
				
				<div id="example"><b><%= link_to 'Create New User', new_user_path %></b> </div>
<!--<div id="comments">
  <%#= render @user %>
</div> -->

app/views/user/login.html.erb
<!DOCTYPE html>
 
<html xmlns="http://www.w3.org/1999/xhtml"> 
 
<head> 
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
	<title>Login</title> 
       <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	    <%= stylesheet_link_tag    "comman",'login' %>
	   </head> 
 
<body> <div id="login">
	    <% if flash[:error] -%>
 			<p class="error"><%=h flash[:error] %></p>
		<% end -%>
	    <% if flash[:message] -%>
 			<p class="warning"><%=h flash[:message] %></p>
		<% end -%>
		<% if flash[:notice] -%>
 		 <p class="success"><%=h flash[:notice] %></p>
	   <% end -%>
		<div id="login_panel">
		<%= form_tag send_login_user_index_path do %>	
			<div class="login_fields">
				<div class="field">
					<label for="">User Name</label>
					<%= text_field 'user','name',:tabindex=>"1"  ,:placeholder=>"user name"%>		
				</div>
				
				<div class="field">
					<label for="password">Password</label>
					<%= password_field 'user','password',:tabindex=>"1"  ,:placeholder=>"password"%>		
				</div>
			</div> 
			
			<div class="login_actions">
				<button type="submit" class="btn btn-orange" tabindex="3">Login</button>
			</div>
		<% end %>
	</div> 		
	
</div> 

</body> 
 
</html>

app/views/user/menu.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>Untitled Document</title>
	</head>
	<body>
	</body>
</html>

app/views/user/new.html.erb
		<%= form_for :user,:url=>{:action=>"create"},:method=> :post  do |f| %>
		
		   <%= render :partial=>"form",:locals=>{:option=>"Create New User",:legend=>"New user",:f=>f}%>
	    <% end %>
       