config/routes.rb
Billing::Application.routes.draw do
  get "client/index"

  get "client/show"
  

     resources :user ,:except=>"show" do
       collection do
         get   :logout
         get   :login
         post  :send_login
       end
   end
   
   
     namespace :master do
       resources :catagories do
          get     :destroy_catagory
       end
       resources :customer do
         get     :destroy_cutomer 
       end

       resources :employees do
         get     :destroy_employee 
       end

       resources :client do
         get     :destroy_client
       end
       resources :item do
         get     :destroy_item
       end
     end

   root :to => 'user#login'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :address_details, :as => 'addressable'
end

app/models/master.rb
module Master
  def self.table_name_prefix
    'master_'
  end
end

app/controllers/master/catagories_controller.rb
class Master::CatagoriesController < ApplicationController
  
  def index
    @catagory = Catagory.new
  end
  
  def edit
    @catagory = Catagory.find(params[:id])
    @action = 'update'
    render  :action => 'index'
  end
  
  def create
    @catagoryy = Catagory.new(params[:catagory])
    if @catagoryy.save && @catagoryy.update_code
      flash[:notice]= " Catagory Created Sucessfully" 
       redirect_to :action => 'index'
    end
  end
  
  def update
    @catorgy = Catagory.find(params[:id])
    if @catorgy.update_attributes(params[:catogary])
      render :action => 'index'
    end
  end
  
   def destroy_catagory
   @delete_catagory = Catagory.find(params[:catagory_id])
   @delete_catagory.destroy
   flash[:notice] = "Catogary  removed sucessfully"
   redirect_to :action=> 'index'
   end
  
end

app/controllers/master/client_controller.rb
class Master::ClientController < ApplicationController
  def index
    @client = Client.new
  end

  def create
    @client = Client.new(params[:client])
    if @client.save && @client.update_code
       @client.address_details.build(params[:address])
       @client.save
       redirect_to(master_client_index_path(@client), :status=> :found, :notice => "New Client created sucessfully") 
     else
      render 'new'
     end
  end
  
  def edit
    @client = Client.find(params[:id])
    @address = @client.address_details.first
    @action = 'update'
    render :action=> 'index'
  end
  
  def destroy_client
    @client = Client.find(params[:client_id])  
    @client.destroy
    flash[:notice] = "Client removed sucessfully"
    render :action=> 'index'
  end
  
  def update
    @clientt = Client.find(params[:id])
    if @clientt.update_attributes(params[:client])
       @clientt.address_details.build(params[:address])
       @clientt.save
       flash[:notice] = "Client Updated sucessfully"
       render :action => 'index'
    end
  end
  
end

app/controllers/master/customer_controller.rb
class Master::CustomerController < ApplicationController
  
  def index
    @customer = Customer.new
    @action = 'create'
  end
  
  def create
    @customer = Customer.new(params[:customer])
    if @customer.save
      @customer.address_details.build(params[:address])
      @customer.save && @customer.update_code
       redirect_to(master_customer_index_path)
    end
  end
  
  def edit
    @customer = Customer.find(params[:id])
    @address = @customer.address_details.last
    @action = 'update'
    render :action=> 'index'
  end
  
  def update
    @customerr = Customer.find(params[:id])
    if @customerr.update_attributes(params[:customer])
      @customerr.address_details.build(params[:address])
      @customerr.save
      redirect_to :action => 'index'
    end
  end
  
 def destroy_cutomer
 @customer = Customer.find(params[:customer_id])
 @customer.destroy
 flash[:notice] = "Customer removed sucessfully"
 render :action=> 'index'
 end

end

app/controllers/master/employees_controller.rb
#include 'abaranji'

class Master::EmployeesController < ApplicationController
  
  def index
    @employee = Employee.new
    @action = 'create'
  end
  
  def new
    @employee = Employee.new(params[:employee])
  end
  
  def create
    @employe = Employee.new(params[:employee])
    if @employe.save && @employe.update_code
      @employe.address_details.build(params[:address])
      @employe.save
      redirect_to(master_employees_path)
    end
  end
  
  def show
    @employee = Employee.find(params[:employee])
  end
  
  def edit
    @employee = Employee.find(params[:id])
    @action = 'update'  
    render :action => 'index', :id => @employee
  end
  
  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      @employee.address_details.build(params[:address])
      @employee.save
      redirect_to :action => 'index', :id => @employee
    end
  end
  
  def destroy_employee
    @employee = Employee.find(params[:employee_id])
    @employee.destroy
    redirect_to :action => 'index'
  end
end

app/controllers/master/item_controller.rb
class Master::ItemController < ApplicationController
    # include CommanMethods
  def index
    @item = Item.new
    
  end
  
  def new
    
  end
  
  def create
    @item = Item.new(params[:item])
    if @item.save
      @item.update_code
      redirect_to :action => 'index',:notice=> @item.item_name + " Created Successfully"
    end
  end
  
  def edit
    @item = Item.find(params[:id])
    @action = 'update'
    render :action=> 'index'
  end
  
  def update
    @itemm = Item.find(params[:id])
    if @itemm.update_attributes(params[:item])
     redirect_to :action => 'index'
    end
  end
  
 def destroy_item
   @item = Item.find(params[:item_id])
   @item.destroy
   flash[:notice] = "Item removed sucessfully"
   redirect_to :action=> 'index'
 end
  
end

app/helpers/master/catagories_helper.rb
module Master::CatagoriesHelper
end

app/helpers/master/client_helper.rb
module Master::ClientHelper
end

app/helpers/master/customer_helper.rb
module Master::CustomerHelper
end

app/helpers/master/employees_helper.rb
module Master::EmployeesHelper
end

app/helpers/master/item_helper.rb
module Master::ItemHelper
end

app/views/master/client/_form.html.erb
<% action = action.blank? ? 'create' : action%>
<fieldset>
  <legend><h3><%= action.titleize + " " + "New Client"  %></h3></legend>
	<%= form_for :client,:url=>{:action=>action},:method=> type,:html => {:class => "form label-inline uniform"} do |f| %>
		<div class="field"><label for="">Client ID </label> <%= f.text_field 'clientid',:size=>"20",:class=>"medium",:value=>action == 'create' ? (Client.generate_code) : client.clientid %></div>
		<div class="field"><label for="">Client Name </label><%= f.text_field 'name',:size=>"30",:class=>"medium"%> </div>
		<div class="field"><label for="">Company Name </label><%= f.text_field 'company_name',:size=>"30",:class=>"medium"%> </div>
		<div class="field"><label for="">TIN Number </label><%= f.text_field 'tin_no',:size=>"30",:class=>"medium"%> </div>
		<div class="field"><label for="">CST Number </label><%= f.text_field 'cst_no',:size=>"30",:class=>"medium"%> </div>
		<div class="field"><label for="">Contact Person </label><%= f.text_field 'contact_person',:size=>"30",:class=>"medium"%> </div>
		<div class="field"><label for="">Mobile Number </label> <%= text_field 'address','mobile_no',:size=>"30",:class=>"medium"%></div>
		<div class="field"><label for="">Telephone Number </label> <%= text_field 'address','telephone_number',:size=>"30",:class=>"medium"%></div>
		<div class="field"><label for="">Addrees </label> <%= text_field 'address','address_1',:size=>"30",:class=>"medium"%></div>
		<div class="field"><label for="">E-Mail ID </label><%= text_field 'address','email',:size=>"30",:class=>"medium"%></div>
		<div class="field"><label for="">City </label> <%= collection_select 'address','city_id',{},:id,:name,{:class=>"medium",:prompt=>"Select the City"}%></div>
		<div class="field"><label for="">State </label>	<%= collection_select 'address','state_id',{},:id,:name,{:class=>"medium",:prompt=>"Select the Catagory"}%></div>
		<div class="field"><label for="">Country </label><%= collection_select 'address','country_id',{},:id,:name,{:class=>"medium",:prompt=>"Select the Catagory"}%></div>
		<div class="field"><label for="">Pincode </label> <%= text_field 'address','pincode',:size=>"20",:class=>"medium"%></div>
		<div class="buttonrow">
			<button class="btn btn-black" style="margin-right: 200px"><%= action_name %></button>
	    </div>	
	<% end %>
</fieldset>

app/views/master/client/edit.html.erb
<%= form_for :client,:url=>master_client_path(@client),:method=>:put do |f| %>
		   <%= render :partial=>"form",:locals=>{:option=>"Edit Client",:legend=>"Update Client",:f=>f}%>
	    <% end %>

app/views/master/client/index.html.erb
		<div class="grid10">
						<%= render :partial=>"form",:locals=>{:action=>@action, :client => @client, :type => @action == 'create' ? 'post' : 'put', :action_name => @action != 'create' ? 'Modify' : 'Add'}%>	

		</div>
		
		<br/><br><br><br>
				
		<table class="data display datatable" id="example">
					<thead>
						<tr>
							<th>S.No</th>
							<th>Client ID</th>
							<th>Client Name</th>
							<th>Email</th>
							<th>Edit</th>
							<th>Delete</th>
						</tr>
					</thead>
					<tbody>
						<% s_no = 0%>
                       <% Client.all.each do |client|%>
					     <% s_no += 1%>
					     <tr class="odd gradeX">
					     	<td><%=s_no%></td>
					     	<td><%= client.clientid %></td>
					     	<td><%= client.name%></td>
							<td><%= client.address_details.first.email%></td>
							<td><%= link_to 'Edit User', edit_master_client_path(client) %></td>
							<td><%= link_to 'Remove User', master_client_destroy_client_path(client.id), :confirm => 'Are you sure?' %></td>
					     </tr>
						 
					   <% end %>
					</tbody>
		</table>
		<div id="example"><b><%= link_to 'Create New Client', new_master_client_path %></b> </div>

app/views/master/client/show.html.erb
<h1>Master::Client#show</h1>
<p>Find me in app/views/master/client/show.html.erb</p>