config/routes.rb
Billing::Application.routes.draw do
  get "client/index"

  get "client/show"
  

     resources :user ,:except=>"show" do
       collection do
         get   :logout
         get   :login
         post  :send_login
       end
   end
   
   
     namespace :master do
       resources :catagories do
          get     :destroy_catagory
       end
       resources :customer do
         get     :destroy_cutomer 
       end

       resources :employees do
         get     :destroy_employee 
       end

       resources :client do
         get     :destroy_client
       end
       resources :item do
         get     :destroy_item
       end
     end

   root :to => 'user#login'

end

app/models/address_detail.rb
class AddressDetail < ActiveRecord::Base
  belongs_to :addressable, :polymorphic => true

end

app/models/catagory.rb
class Catagory < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :address_details, :as => 'addressable'
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :address_details, :as => 'addressable'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
    has_many :address_details, :as => 'addressable', :dependent => :delete_all 
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/master.rb
module Master
  def self.table_name_prefix
    'master_'
  end
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/uniqueid.rb
class Uniqueid < ActiveRecord::Base
  
  
end

app/models/user.rb
# require 'my_module'
# load 'my_module.rb'

class User < ActiveRecord::Base
   include CommanMethods
   has_many :address_details, :as => 'addressable'
   
   
   attr_accessor    :password
   attr_accessible  :name,:password

  
  validates_presence_of :email,:password,:name
  validates_uniqueness_of :name
  validates_confirmation_of :password,:email
   
   
   before_create :change_password
   after_create :unchange_password
   

   def change_password
    self.hashed_password = User.hash_pasword(self.password)
  end
  
  def unchange_password
    password = nil
  end
  
  def self.login(name,password)
    hashed_pasword  = hash_pasword(password || "")
    self.find(:first,:conditions =>["name =? and hashed_password =?",name,hashed_pasword])
  end
  
  def try_to_login
    User.login(self.name,self.password)
  end
  
  private  #------------------------
  
   def self.hash_pasword(password)
     Digest::SHA1.hexdigest(password)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery
 before_filter :authorize_access , :except => [:login, :send_login]
   layout 'menu',:except=>['login'] 
  
  
  def get_code
    Uniqueid.where(:class_name => self.name).last
  end  
  private #-----------------------
  
  
  def authorize_access
   if not session[:user_id]
      flash[:message] = "please Login to access other links"
      redirect_to(:controller => 'user', :action => 'login')
      return  false
   end  
 end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController

#  respond_to :html, :xml, :json
  
  def index
    @user = User.all
    
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def login
  end

  def send_login
    @user = User.new(params[:user])
    logged_in_user = @user.try_to_login
    if logged_in_user
      session[:user_id] = logged_in_user.id
      flash[:notice] = "You are now Logged in"
      redirect_to(user_index_path(@user), :status=> :found, :notice => "You hav loged in ") 
      
    else
      flash[:error] = "Incorrect Username and password"
      redirect_to login_user_index_path
    end
  end

  def menu
  end

  def create
     @user = User.new(params[:user])
     @user.email=  params[:user][:email]
     if @user.save
       redirect_to(user_index_path(@user), :status=> :found, :notice => "New User created sucessfully") 
     else
      render 'new'
     end
  end
 
 def destroy
  @user = User.find(params[:id])
  @user.destroy
  redirect_to(user_index_path(@user), :status=> :found, :notice => "User removed sucessfully")
 end

 def update
  @user = User.find(params[:id])
   @user.update_attributes(params[:user])
    if @user.update_attributes(params[:user])
      
       redirect_to(user_index_path(@user), :status=> :found, :notice => @user.name + "Details updated sucessfully") 
     else
      render 'edit'
     end
 end

 def logout
    session[:user_id] = nil
     flash[:notice] = "you are Logged out sucessfully"
     redirect_to :action => 'login'
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/master/item_helper.rb
module Master::ItemHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Billing</title>
  <%#= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:error] -%>
 			<p class="error"><%=h flash[:error] %></p>
		<% end -%>
		<% if flash[:notice] -%>
 		 <p class="success"><%=h flash[:notice] %></p>
		<% end -%>
		
<%= yield %>

</body>
</html>

app/views/layouts/menu.html.erb
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"> 
 
<head> 
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
	<title>Client</title> 

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "js/jquery/jquery-1.5.2.min.js","js/jquery/jquery-ui-1.8.12.custom.min.js","js/misc/excanvas.min.js","js/jquery/facebox.js","js/jquery/jquery.visualize.js","js/jquery/jquery.dataTables.min.js","js/jquery/jquery.tablesorter.min.js","js/jquery/jquery.uniform.min.js", "js/jquery/jquery.placeholder.min.js" %>
  <%= javascript_include_tag "js/widgets.js","js/dashboard.js" %>
  <%= stylesheet_link_tag "comman"%>
  <%= stylesheet_link_tag  'css/layout' %>
  <%= stylesheet_link_tag    "css/ui-darkness/jquery-ui-1.8.12.custom.css","css/plugin/jquery.visualize.css","css/plugin/facebox.css","css/plugin/uniform.default.css","css/plugin/dataTables.css","css/custom.css" %>
  <%#= csrf_meta_tags %>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head> 
 
<body> 

<div id="wrapper">
	
	<div id="top">
		
		<div class="content_pad">			
			<ul class="right">
				<li><a href="@" class="top_icon"><span class="ui-icon ui-icon-person"></span>Logged in as <b style="color:red"><%= User.find(session[:user_id]).name.titleize if session[:user_id]%></b></a></li>
				<li><a href="@">Settings</a></li>
				<li><%= link_to 'Logout',logout_user_index_path%></li>
			</ul>
		</div> 
		
	</div> 
	
	<div id="header">
		<div class="content_pad">
			<h1><a href="@">Logo</a></h1>
			
			<ul id="nav">
				<li class="nav_current nav_icon"><a href="@"><span class="ui-icon ui-icon-home"></span>Home</a></li>
				<li class="nav_dropdown nav_icon"><a href=""><span class="ui-icon ui-icon-gripsmall-diagonal-se"></span>Master</a>
				<div class="nav_menu">			
						<ul>
							<li><%= link_to "Item", master_item_index_path%></a></li>
							<li><%= link_to 'Catagory',master_catagories_path %></li>	
							<li><%= link_to "Customer",master_customer_index_path%></li>
							<li><%= link_to "Client",master_client_index_path%></li>							
							<li><a href="">Supplier</a></li>	
							<li><%= link_to 'Employee',master_employees_path %></li>						
							<li><a href=""></a></li>
						</ul>
				  </div>
				</li>
				
				<li class="nav_dropdown nav_icon"><a href=""><span class="ui-icon ui-icon-gear"></span>Billing</a>
				<div class="nav_menu">			
						<ul>
							<li><a href="">Sales Billing</a></li>	
							<li><a href="">Sales Print</a></li>
							<li><a href="">Service Billing</a></li>	
							<li><a href="">Service Print</a></li>
						</ul>
				  </div>
				</li>
				<li class="nav_dropdown nav_icon"><a href=""><span class="ui-icon ui-icon-gear"></span>Day Book</a>
				<div class="nav_menu">			
						<ul>
							<li><a href="">Payment</a></li>	
							<li><a href="">Receipt</a></li>
						</ul>
				  </div>
				</li>
				<li class="nav_icon"><a href=""><span class="ui-icon ui-icon-signal"></span>Reports</a></li>
				</div>
				
				</li>
			</ul>
		</div>
		
		
	</div> <!-- #header -->	
	

<div id="masthead">

</div>
	    
	<div id="content" class="grid" style="height: auto !important; min-height: 460px;">
		
		<% if flash[:error] -%>
 			<p class="validation"><%=h flash[:error] %></p>
		<% end -%>
		<% if flash[:notice] -%>
 		 <p class="success"><%=h flash[:notice] %></p>
		<% end -%>
	    <%= yield%>
	
	</div>
	
	<div id="footer">		
		<div class="content_pad">			
			<p><a href="">Company Name</a>. Powered by <a href="">Xplore</a>.</p>
		</div>
	</div> 
	
</div> 


<script>
	
$(document).ready ( function () 
{
	Dashboard.init ();			
		
	$('#datepicker').datepicker();
	
});

</script>

</body> 
 
</html>